FROM php:8.1-fpm-buster
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
	php composer-setup.php && \
	php -r "unlink('composer-setup.php');" && \
	mv composer.phar /usr/local/bin/composer

RUN apt-get update && \
    apt-get install -y zlib1g-dev libpng-dev libjpeg62-turbo-dev libfreetype6-dev libzip-dev git libicu-dev zip
RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN docker-php-ext-install -j$(nproc) gd
RUN docker-php-ext-install zip bcmath pdo pdo_mysql gettext exif intl

USER root

RUN apt-get update &&\
    apt-get install -y --no-install-recommends gnupg &&\
    curl -sL https://deb.nodesource.com/setup_17.x | bash - &&\
    apt-get update &&\
    apt-get install -y --no-install-recommends nodejs

WORKDIR /code
ENV PATH="$PATH:./node_modules/.bin"

RUN apt-get update && apt-get install -y --no-install-recommends supervisor

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
